/**
 * Markdown reporter - generates a results table suitable for GitHub PR comments.
 */

import type { EvalRun } from '../types.js';
import type { Reporter } from './base.js';

export class MarkdownReporter implements Reporter {
  report(run: EvalRun): string {
    const { summary, results, startedAt, finishedAt, gitBranch, gitRef } = run;

    const lines: string[] = [];

    // Header
    lines.push('## Prompt CI Eval Results');
    lines.push('');

    // Metadata
    const meta: string[] = [`**Run ID:** \`${run.id}\``];
    if (gitBranch) meta.push(`**Branch:** \`${gitBranch}\``);
    if (gitRef) meta.push(`**Ref:** \`${gitRef}\``);
    meta.push(`**Started:** ${startedAt}`);
    meta.push(`**Finished:** ${finishedAt}`);
    lines.push(meta.join(' | '));
    lines.push('');

    // Summary cards
    const passRate =
      summary.totalTests > 0
        ? ((summary.passed / summary.totalTests) * 100).toFixed(1)
        : '0.0';
    lines.push('### Summary');
    lines.push('');
    lines.push(
      `| Tests | Passed | Failed | Pass Rate | Avg Score | Total Cost | Total Time |`,
    );
    lines.push(`|-------|--------|--------|-----------|-----------|------------|------------|`);
    lines.push(
      `| ${summary.totalTests} | ${summary.passed} | ${summary.failed} | ${passRate}% | ${summary.avgScore.toFixed(3)} | $${summary.totalCost.toFixed(4)} | ${(summary.totalDurationMs / 1000).toFixed(2)}s |`,
    );
    lines.push('');

    // Results table
    lines.push('### Test Results');
    lines.push('');
    lines.push(
      '| Prompt | Test | Status | Score | Cost | Latency |',
    );
    lines.push('|--------|------|--------|-------|------|---------|');

    for (const result of results) {
      const status = result.passed ? '✅ Pass' : '❌ Fail';
      const cost = `$${result.response.cost.toFixed(4)}`;
      const latency = `${result.response.latencyMs}ms`;
      lines.push(
        `| ${escapeMarkdown(result.promptName)} | ${escapeMarkdown(result.testCase.name)} | ${status} | ${result.score.toFixed(3)} | ${cost} | ${latency} |`,
      );
    }

    lines.push('');

    // Footer
    lines.push(
      `---`,
    );
    lines.push(
      `*Generated by [Prompt CI](https://github.com/prompt-ci) · ${new Date(finishedAt).toUTCString()}*`,
    );

    return lines.join('\n');
  }
}

function escapeMarkdown(text: string): string {
  return text.replace(/[|`*_[\]]/g, '\\$&');
}
